CREATE TABLE rtrw_file (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(36) UNIQUE NULL,
    rdtr_group_id BIGINT,
    rdtr_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
