CREATE TABLE zlp_file (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(36) UNIQUE NULL,
    zlp_group_id BIGINT,
    zlp_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
